### PR TITLE
Convert to TypeScript

### LINKED ISSUE #3: Rewrite in TypeScript and publish a .d.ts file
Should close this 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25009

### PR DESCRIPTION
**Pull request by mohsen1**
Fixes #3

### CODE REVIEW

**Comment by mohsen1** [comment]
When linking to Webpack and deleting handcrafted types I got following errors:


```
 !  ~/P/webpack   master *$  yarn type-lint                                                                     4479ms  Sun Apr 15 16:56:24 2018
yarn run v1.5.1
$ tsc --pretty
lib/debug/ProfilingPlugin.js:341:25 - error TS2339: Property 'counter' does not exist on type 'Tracer'.

341                     const id = ++tracer.counter;
                                            ~~~~~~~


lib/debug/ProfilingPlugin.js:342:12 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

342                     tracer.trace.begin({
                               ~~~~~


lib/debug/ProfilingPlugin.js:349:13 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

349                             tracer.trace.end({
                                       ~~~~~


lib/debug/ProfilingPlugin.js:360:25 - error TS2339: Property 'counter' does not exist on type 'Tracer'.

360                     const id = ++tracer.counter;
                                            ~~~~~~~


lib/debug/ProfilingPlugin.js:361:12 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

361                     tracer.trace.begin({
                               ~~~~~


lib/debug/ProfilingPlugin.js:368:13 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

368                             tracer.trace.end({
                                       ~~~~~


lib/debug/ProfilingPlugin.js:379:25 - error TS2339: Property 'counter' does not exist on type 'Tracer'.

379                     const id = ++tracer.counter;
                                            ~~~~~~~


lib/debug/ProfilingPlugin.js:386:12 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

386                     tracer.trace.begin({
                               ~~~~~


lib/debug/ProfilingPlugin.js:395:13 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

395                             tracer.trace.end({
                                       ~~~~~


lib/debug/ProfilingPlugin.js:402:12 - error TS2339: Property 'trace' does not exist on type 'Tracer'.

402                     tracer.trace.end({
                               ~~~~~


error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c tsc --pretty
Directory: /Users/mazimi/Projects/webpack
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mazimi/Projects/webpack/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 !  ~/P/webpack   master *$                                                                                     4657ms  Sun Apr 15 16:56:31 2018
```

I don't see `trace` and `counter` members in the code but this is somehow working in Webpack.

@TheLarkInn what's going on?

**Comment by samccone** [comment]
Thanks for putting this PR together I will review it for you this week!

**Comment by mohsen1** [comment]
Ping @samccone

**Comment by samccone** [comment]
Half way though it this weekend, there are some other build related changes that need to be made :)

**Comment by samccone** [comment]
Hi @mohsen1 Can you please enable me to push to this pull request?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests

I would like to layer my changes in here.
https://github.com/samccone/chrome-trace-event/commits/pr/4


Thank you.

**Comment by mohsen1** [comment]
@samccone 
screen shot 2018-04-24 at 8 05 34 am

**Comment by samccone** [comment]
After another review I think we are now good to go.

Thanks for kicking this work off @mohsen1

**Pull request merged**
